[{"name": "test.test_swedish_and_foreigners.SwedishAndForeigners.test_called", "status": "passed", "message": "", "passed": true, "points": ["p04-05.1"], "backtrace": []}, {"name": "test.test_swedish_and_foreigners.SwedishAndForeigners.test_columns", "status": "failed", "message": "\nArrays are not equal\nIncorrect column names!\nMismatched elements: 2 / 3 (66.7%)\n x: array(['Population', 'Share of foreign citizens of the population, %',\n       'Share of Swedish-speakers of the population, %'], dtype=object)\n y: array(['Population', 'Share of Swedish-speakers of the population, %',\n       'Share of foreign citizens of the population, %'], dtype='<U46')", "passed": false, "points": ["p04-05.1"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part04-e05_swedish_and_foreigners/test/test_swedish_and_foreigners.py\", line 29, in test_columns\n    err_msg=\"Incorrect column names!\")\n", "  File \"/home2/anacondad3/lib/python3.7/site-packages/numpy/testing/_private/utils.py\", line 936, in assert_array_equal\n    verbose=verbose, header='Arrays are not equal')\n", "  File \"/home2/anacondad3/lib/python3.7/site-packages/numpy/testing/_private/utils.py\", line 846, in assert_array_compare\n    raise AssertionError(msg)\n"]}, {"name": "test.test_swedish_and_foreigners.SwedishAndForeigners.test_content", "status": "failed", "message": "11.5 != 89.7 : Value on row 'EckerÃ¶' column 'Share of foreign citizens of the population, %' is not correct!", "passed": false, "points": ["p04-05.1"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part04-e05_swedish_and_foreigners/test/test_swedish_and_foreigners.py\", line 42, in test_content\n    df.index[i], df.columns[i]))\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 852, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 845, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}, {"name": "test.test_swedish_and_foreigners.SwedishAndForeigners.test_index", "status": "passed", "message": "", "passed": true, "points": ["p04-05.1"], "backtrace": []}, {"name": "test.test_swedish_and_foreigners.SwedishAndForeigners.test_shape", "status": "passed", "message": "", "passed": true, "points": ["p04-05.1"], "backtrace": []}]